#!/usr/bin/env bash
#
# Grafana radiator kiosk — one-shot installer.
#
# Copy this single file to the kiosk machine and run it. It will:
#   1. install nginx + curl + chromium
#   2. write a local reverse proxy that injects a Grafana service-account token
#   3. install a Chromium kiosk launcher + systemd --user unit (restarts on crash)
#   4. disable screen blanking
#
# The browser only ever talks to http://localhost:<port>; the proxy adds the
# Authorization: Bearer header that browsers can't send themselves.
#
# Run interactively:
#   ./install.sh
# Or non-interactively (any unset value is prompted for):
#   GRAFANA_ORIGIN=https://grafana.example.com \
#   GRAFANA_TOKEN=glsa_xxx \
#   DASHBOARD_PATH=/d/abc123/my-board \
#   ./install.sh
#
set -euo pipefail

# --- settings (override via env) -------------------------------------------
PROXY_PORT="${PROXY_PORT:-8080}"
REFRESH="${REFRESH:-30s}"
KIOSK_MODE="${KIOSK_MODE:-kiosk}"          # 'kiosk' (no chrome) or 'kiosk=tv' (keep top bar)
BIN_DIR="$HOME/.local/bin"
CONF_DIR="$HOME/.config/radiator"
UNIT_DIR="$HOME/.config/systemd/user"
LAUNCHER="$BIN_DIR/radiator-kiosk.sh"
NGINX_CONF="/etc/nginx/conf.d/radiator.conf"

# --- helpers ---------------------------------------------------------------
say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m  ok\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }
ask()  { local p="$1" v="$2" d="${3:-}" r; if [[ -n "$d" ]]; then read -rp "$p [$d]: " r; echo "${r:-$d}"; else read -rp "$p: " r; echo "$r"; fi; }

[[ $EUID -eq 0 ]] && die "Run as your normal desktop user (the script calls sudo where needed), not root."
command -v sudo >/dev/null || die "sudo is required."

# --- gather config ---------------------------------------------------------
say "Configuration"
GRAFANA_ORIGIN="${GRAFANA_ORIGIN:-$(ask 'Grafana URL (https://host, no trailing path)' GRAFANA_ORIGIN)}"
GRAFANA_ORIGIN="${GRAFANA_ORIGIN%/}"
[[ "$GRAFANA_ORIGIN" =~ ^https?:// ]] || die "Grafana URL must start with http:// or https://"
GRAFANA_HOST="${GRAFANA_ORIGIN#*://}"

if [[ -z "${GRAFANA_TOKEN:-}" ]]; then
    read -rsp "Grafana service-account token (glsa_...): " GRAFANA_TOKEN; echo
fi
[[ -n "$GRAFANA_TOKEN" ]] || die "A token is required."

# A single dashboard (/d/<uid>/<slug>) or a playlist to rotate several
# (/playlists/play/<uid> — create the playlist + interval in Grafana first).
DASHBOARD_PATH="${DASHBOARD_PATH:-$(ask 'Dashboard or playlist path (/d/<uid>/<slug> or /playlists/play/<uid>)' DASHBOARD_PATH)}"
[[ "$DASHBOARD_PATH" == /* ]] || DASHBOARD_PATH="/$DASHBOARD_PATH"

# Playlists rotate server-side and carry each dashboard's own refresh, so don't
# append &refresh to them.
if [[ "$DASHBOARD_PATH" == /playlists/* ]]; then
    RADIATOR_URL="http://localhost:${PROXY_PORT}${DASHBOARD_PATH}?${KIOSK_MODE}"
else
    RADIATOR_URL="http://localhost:${PROXY_PORT}${DASHBOARD_PATH}?${KIOSK_MODE}&refresh=${REFRESH}"
fi
say "Kiosk will open: $RADIATOR_URL"

# --- 1. packages -----------------------------------------------------------
say "Installing packages (nginx, curl, chromium)"
sudo apt-get update -qq
# Chromium is named differently across distros; install whichever exists.
CHROME_PKG="chromium"
apt-cache show chromium >/dev/null 2>&1 || CHROME_PKG="chromium-browser"
sudo apt-get install -y -qq nginx curl "$CHROME_PKG"
ok "packages installed"

# Resolve the chromium binary name for the launcher.
CHROME=""
for c in chromium chromium-browser google-chrome google-chrome-stable; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
[[ -n "$CHROME" ]] || die "No chromium binary found after install."
ok "browser: $CHROME"

# --- 2. nginx reverse proxy ------------------------------------------------
say "Writing reverse proxy to $NGINX_CONF"
sudo tee "$NGINX_CONF" >/dev/null <<EOF
# Generated by radiator install.sh. Contains a secret token — keep mode 600.
map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 127.0.0.1:${PROXY_PORT};
    server_name localhost;

    set \$grafana_host   "${GRAFANA_HOST}";
    set \$grafana_origin "${GRAFANA_ORIGIN}";
    set \$grafana_token  "${GRAFANA_TOKEN}";

    location / {
        # Literal host (not a variable): nginx resolves it at load time. A
        # variable here would need a separate 'resolver' directive or 502s.
        proxy_pass        ${GRAFANA_ORIGIN};
        proxy_set_header  Host          \$grafana_host;
        proxy_set_header  Authorization "Bearer \$grafana_token";
        proxy_set_header  X-Real-IP     \$remote_addr;

        proxy_ssl_server_name on;
        proxy_ssl_name        \$grafana_host;

        proxy_redirect \$grafana_origin/ /;

        proxy_http_version 1.1;
        proxy_set_header   Upgrade    \$http_upgrade;
        proxy_set_header   Connection \$connection_upgrade;

        proxy_read_timeout 1h;
        proxy_buffering    off;
    }
}
EOF
sudo chmod 600 "$NGINX_CONF"
say "Testing + reloading nginx"
sudo nginx -t
sudo systemctl enable --now nginx
sudo systemctl reload nginx
ok "nginx running"

say "Verifying the proxy authenticates to Grafana"
if curl -sf -o /dev/null "http://localhost:${PROXY_PORT}/api/health"; then
    ok "proxy reaches Grafana (/api/health is healthy)"
else
    printf '\033[1;33m  warn\033[0m /api/health did not return success. Check the token/URL.\n'
    printf '       Try: curl -i http://localhost:%s/api/health\n' "$PROXY_PORT"
fi

# --- 3. kiosk launcher -----------------------------------------------------
say "Writing kiosk launcher to $LAUNCHER"
mkdir -p "$BIN_DIR" "$CONF_DIR"
cat > "$CONF_DIR/radiator.env" <<EOF
RADIATOR_URL="${RADIATOR_URL}"
PROXY_PORT=${PROXY_PORT}
EOF

cat > "$LAUNCHER" <<'LAUNCH'
#!/usr/bin/env bash
# Launch Chromium fullscreen on the Grafana dashboard, keep the screen awake.
set -euo pipefail
source "$HOME/.config/radiator/radiator.env"

# Keep the display awake (X11).
if command -v xset >/dev/null 2>&1; then
    xset s off || true; xset s noblank || true; xset -dpms || true
fi

# Wait for the local proxy.
until curl -sf -o /dev/null "http://localhost:${PROXY_PORT}/api/health"; do sleep 2; done

CHROME=""
for c in chromium chromium-browser google-chrome google-chrome-stable; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done

PROFILE="$HOME/.config/radiator-chromium"
mkdir -p "$PROFILE/Default"
[[ -f "$PROFILE/Default/Preferences" ]] && \
    sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"Crashed"/"exit_type":"Normal"/' \
        "$PROFILE/Default/Preferences" || true

# Kill any stale Chromium on THIS profile so a relaunch doesn't hand off + exit.
pkill -f -- "--user-data-dir=$PROFILE" 2>/dev/null || true

# --kiosk with URL as a positional arg. Do NOT add --app (causes a second
# window / flicker on startup).
exec "$CHROME" \
    --user-data-dir="$PROFILE" \
    --kiosk \
    --noerrdialogs --disable-infobars --disable-session-crashed-bubble \
    --disable-features=TranslateUI --check-for-update-interval=31536000 \
    --no-first-run --autoplay-policy=no-user-gesture-required \
    "$RADIATOR_URL"
LAUNCH
chmod +x "$LAUNCHER"
ok "launcher installed"

# --- 4. systemd --user unit ------------------------------------------------
say "Installing systemd --user service (auto-restart on crash)"
mkdir -p "$UNIT_DIR"
cat > "$UNIT_DIR/radiator-kiosk.service" <<EOF
[Unit]
Description=Grafana Radiator Kiosk (Chromium fullscreen)
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=${LAUNCHER}
Restart=always
RestartSec=3
Environment=DISPLAY=:0
Environment=XAUTHORITY=%h/.Xauthority

[Install]
WantedBy=graphical-session.target
EOF

systemctl --user daemon-reload
systemctl --user enable radiator-kiosk.service
# Lingering: lets the user service start at boot without an interactive login.
sudo loginctl enable-linger "$USER"
ok "service enabled"

# --- 5. Cinnamon screen-blank / screensaver / power ------------------------
# Cinnamon (Linux Mint) has its own gsettings schemas; disable everything that
# would blank or lock the radiator. Runs in this user's dbus session.
if command -v gsettings >/dev/null 2>&1; then
    say "Disabling Cinnamon screensaver / screen blanking / power-down"
    gsettings set org.cinnamon.desktop.session idle-delay 0 2>/dev/null || true
    gsettings set org.cinnamon.desktop.screensaver lock-enabled false 2>/dev/null || true
    gsettings set org.cinnamon.desktop.screensaver idle-activation-enabled false 2>/dev/null || true
    gsettings set org.cinnamon.settings-daemon.plugins.power idle-dim false 2>/dev/null || true
    gsettings set org.cinnamon.settings-daemon.plugins.power sleep-display-ac 0 2>/dev/null || true
    gsettings set org.cinnamon.settings-daemon.plugins.power sleep-display-battery 0 2>/dev/null || true
    gsettings set org.cinnamon.settings-daemon.plugins.power sleep-inactive-ac-timeout 0 2>/dev/null || true
    ok "Cinnamon idle/blank/lock disabled"
fi

# --- done ------------------------------------------------------------------
say "Done."
cat <<EOF

Next:
  - Enable autologin for this user: Menu -> Login Window -> Users tab ->
    "Automatic login" = this user. (Or set autologin-user in
    /etc/lightdm/lightdm.conf under [Seat:*].)
  - Screensaver/blanking/power-down were just disabled via gsettings. If the
    screen still blanks, double-check Menu -> Screensaver and Menu -> Power.

Start it now without rebooting:
    systemctl --user start radiator-kiosk.service
Watch logs:
    journalctl --user -u radiator-kiosk -f
Change dashboard later:
    edit $CONF_DIR/radiator.env  then  systemctl --user restart radiator-kiosk
Rotate the token:
    sudo \$EDITOR $NGINX_CONF  then  sudo systemctl reload nginx
EOF
